# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  schedule: [{cron: "25 * * * *"}]
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: update render website
        run: curl -X POST https://api.render.com/deploy/srv-ceu4kk2rrk01m31dqjm0?key=OiWffyNUt7M
